# Generated by Django 5.2 on 2025-05-02 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feestructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['term_fee__fee_class__name', 'term_fee__term', 'category'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PP1', 'PP1'), ('PP2', 'PP2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5')], max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=10)),
                ('fee_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.feestructureclass')),
            ],
            options={
                'ordering': ['fee_class__name', 'term'],
                'unique_together': {('fee_class', 'term')},
            },
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
        migrations.AddField(
            model_name='feeitem',
            name='term_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.termfee'),
        ),
        migrations.AlterUniqueTogether(
            name='feeitem',
            unique_together={('term_fee', 'category')},
        ),
    ]
