# Generated by Django 5.2 on 2025-04-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_student_class_enrolled_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=11)),
                ('role', models.CharField(choices=[('Security', 'Security'), ('Cook', 'Cook'), ('Secretary', 'Secretary'), ('Cleaner', 'Cleaner'), ('Lab_Technician', 'Lab_Technician'), ('Nurse', 'Nurse'), ('Social_Media_Manager', 'Social_Media_Manager')], max_length=20)),
                ('date_of_employment', models.DateField()),
            ],
        ),
    ]
