# Generated by Django 5.2 on 2025-04-23 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
    ]
