# Generated by Django 5.2 on 2025-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacher_first_name_remove_teacher_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
