# Generated by Django 5.2 on 2025-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='default_username', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='default_teacher_username', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_enrolled',
            field=models.CharField(choices=[('PP 1', 'PP 1'), ('PP 2', 'PP 2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], max_length=10),
        ),
    ]
